### ISSUE TITLE
Required products to install BCM94360CS2 into the laptop

### ISSUE THREAD

**Issue by andreswhr** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#7]
Good day,

First of all I wanted to thank you for your hard work in this project. I'm looking to install Hackintosh on my i5-8250u Matebook D 2018. As I need to replace the Wifi/BT Card, I was looking the picture you attached but I'm having trouble to recognize what I need to buy. As I can see, you have the BCM94360CS2 card, a M2 NGFF adaptor, and some kind of cable because it doesn't fit in the original position. Can you please list, besides the BCM94360CS2 card, what else did you buy so it all worked together.

Again thank you a lot, and have a nice day.

**Comment by andreswhr** [comment]
https://es.aliexpress.com/item/32946029345.html?spm=a2g0s.8937460.0.0.2a1d2e0ekI2vVV

Is this exactly what I need to adapt the new Wifi/bt card? Thank you.

**Comment by Zero-zer0** [comment]
Hello!

Thank you for your support!

1. The adapter is different for what you've found. Actually the one I'm using has an **m.2 NGFF A+E key 22*30 card** with a FFC slot, in order to connect with another card with **Apple 6+12 pin slot** for some removable Apple wireless cards like BCM94360CS2. </br>Things can be done by only one adapter and some tapes. There is no need for a Mini-PCIe slot for a secondary adapter. 

2. I have found an adapter exactly the same to the one I'm using on AliExpress:[link](https://es.aliexpress.com/item/4000291280536.html?spm=a2g0o.productlist.0.0.5db01c7b2QBTqJ&algo_pvid=58e27c50-cfd3-4b1d-a47b-0844639975b7&algo_expid=58e27c50-cfd3-4b1d-a47b-0844639975b7-20&btsid=0b86d81615848848784222166ea9b6&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_). </br>Certainly, you can search `BCM94360` for more retailers. However, the adapter with a single card can't be placed properly for it is a 22*40 or longer. Just find the adapter with FFC for extending.

Hope you will enjoy with your hackintosh and everything goes well! Have a nice day!

**Comment by andreswhr** [comment]
Thanks for the fast answer, I already purchased the adapter you sent me over AliExpress and I will report once I got everything installed. 

Thank you again, have a nice day!
